### ISSUE TITLE
With Apparmor profile enabled for Chromium, ptrace protection with Yama is disabled

### ISSUE THREAD

**Issue by h4xor666** [krathalan/apparmor-profiles#1]
With the Chromium apparmor profile provided, chrome://sandbox tells me that ptrace protection with yama LSM (broker and non-broker) are not on. Is this expected behavior? With the profile disabled, both of those options say they are enabled. I'm not super experienced with apparmor profiles yet, mind you, so I might have the wrong idea about it.

**Comment by krathalan** [comment]
Sorry for the delay; the issue seemed to be related only to Chromium seeing if it was actually sandboxed this way or not, not actually if the specific sandbox was working. In either case it should be fixed in commit 4f3cee6a3707221dff291a3204324ce5466557cd
