### ISSUE TITLE
Unable to play YouTube videos through MPV with youtube-dl.

### ISSUE THREAD

**Issue by coolio321** [krathalan/apparmor-profiles#3]
After installing the MPV apparmor profile and not modifying the profile, I get the following error after trying to play a YouTube video with MPV:

[ipc] Could not bind IPC socket
[ytdl_hook]
[ytdl_hook] youtube-dl failed: not found or not enough permissions
Failed to recognize file format.

It plays the same video fine when the profile is disabled. Any ideas on what could cause this? I don't use a fork of youtube-dl like yt-dlp.

**Comment by krathalan** [comment]
I just pushed a new commit, please try with the latest `mpv` profile from 5d832fb. I need to update the readme; I just deprecated the `youtube-dl` profile and I want to make a new profile for `yt-dlp` soon.

**Comment by coolio321** [comment]
> I just pushed a new commit, please try with the latest `mpv` profile from [5d832fb](https://github.com/krathalan/apparmor-profiles/commit/5d832fb9b02f15e2812d7915614c25fa9d6fffdf). I need to update the readme; I just deprecated the `youtube-dl` profile and I want to make a new profile for `yt-dlp` soon.

That seems to have fixed it! Thank you for responding so quickly!
