### ISSUE TITLE
Discord issues

### ISSUE THREAD

**Issue by Sacro** [krathalan/apparmor-profiles#7]
Unable to open /opt/discord/libffmpeg.so

**Comment by Sacro** [comment]
It seems to be walking `/proc` AppArmor clearly doesn't like that

**Comment by krathalan** [comment]
Unfortunately it seems discord changes what it needs access to a lot, and frankly I don't have the energy to keep up. Honestly I would recommend using the Discord flatpak with flatseal: https://github.com/tchx84/flatseal
